import type { Metadata } from "next";
import TopBar from "@/components/layout/TopBar";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import FloatingChat from "@/components/common/FloatingChat";



import "./globals.css";
import HeroSlider from "@/components/home/HeroSlider";

import HeroSliderClient from "@/components/home/HeroSliderClient";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
          <TopBar />
          <Navbar />
      
           <HeroSliderClient/>

          {children}
                <Footer />
                 <FloatingChat />

      </body>
    </html>
  );
}
